apiVersion: v1
kind: Pod
metadata:
  name: gateway
spec:
  containers:
    - name: gateway
      image: tgwsoftwarecontainerregistry.azurecr.io/tgw-oauth-gateway:1.1.0-r00124
      imagePullPolicy: ifNotPresent
      resources:
        limits:
          memory: 1Gi
      securityContext: {}
      ports:
        - containerPort: 443
          hostPort: 443
      volumeMounts:
        - mountPath: /app/appsettings.json:Z
          name: gateway-config-data
        - mountPath: /app/fullchain.crt:Z
          name: gateway-ssl-cert
        - mountPath: /app/privkey.key:Z
          name: gateway-ssl-key
  volumes:
    - name: gateway-config-data
      hostpath:
        path: /home/podman/conf/appsettings.json
        type: File
    - name: gateway-ssl-cert
      hostpath:
        path: /home/podman/certs/c022podfat0101.tgwdev.internal.crt
        type: File
    - name: gateway-ssl-key
      hostpath:
        path: /home/podman/certs/c022podfat0101.tgwdev.internal.key
        type: File
  restartPolicy: Never
