kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.deployment.name }}
    app.kubernetes.io/component: {{ .Values.deployment.name }}
    app.kubernetes.io/instance: {{ .Values.deployment.name }}
    app.kubernetes.io/name: {{ .Values.deployment.name }}
  annotations:
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod
spec:
  # define primary URL in values.yaml
  host: {{ .Values.deployment.domain }}
  to:
    kind: Service
    name: {{ .Values.deployment.name }}
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
