kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.deployment.configmap_name }}
  namespace: {{ .Values.global.namespace }}
data:
  fluent.conf: |-
    <source>
      @type http
      port 8080
      bind 0.0.0.0
      body_size_limit 32m
      keepalive_timeout 10s
      cors_allow_origins ["*"]
    </source>

    <match **>
      @type stdout
    </match>
