export interface Env {
  VITE_APP_I18N_LOCALE: string
  VITE_APP_I18N_FALLBACK_LOCALE: string
  VITE_APP_LOGGER_SERVICE: string
  BASE_URL: string
  VITE_APP_PORTAL_URL: string
  VITE_APP_DEVELOPMENT_KEYCLOAK_ACIVATED: string
  VITE_APP_DEVELOPMENT_KEYCLOAK_URL: string
  VITE_APP_DEVELOPMENT_KEYCLOAK_REALM_NAME: string
  VITE_APP_DEVELOPMENT_KEYCLOAK_CLIENT_NAME: string
  VITE_APP_SAMPLEAPI_URL: string
}

// variable holds environment variables which are loaded from the server side
export const env: Env = {
  VITE_APP_I18N_LOCALE: '',
  VITE_APP_I18N_FALLBACK_LOCALE: '',
  VITE_APP_LOGGER_SERVICE: '',
  BASE_URL: '',
  VITE_APP_PORTAL_URL: '*',
  VITE_APP_DEVELOPMENT_KEYCLOAK_ACIVATED: '',
  VITE_APP_DEVELOPMENT_KEYCLOAK_URL: '',
  VITE_APP_DEVELOPMENT_KEYCLOAK_REALM_NAME: '',
  VITE_APP_DEVELOPMENT_KEYCLOAK_CLIENT_NAME: '',
  VITE_APP_SAMPLEAPI_URL: '',
}
